builders:
  hive2sqlGenerator:
    import: "package:hive2sql/hive2sql.dart"
    builder_factories: ["hive2sqlGenerator"]
    build_extensions: { ".dart": ["hive2sql.g.part"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  # hive2sqlBuilder:
  #   import: "package:hive2sql/hive2sql.dart"
  #   builder_factories: ["hive2sqlBuilder"]
  #   build_extensions:
  #     .dart:
  #       - .g.dart
  #   build_to: source
  #   auto_apply: root_package
