name: hive2sql
description: Convert Hive files to SQLite helper files.
version: 0.0.1
homepage: https://github.com/LOLwierd/hive2sql
repository: https://github.com/LOLwierd/hive2sql

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  path: ^1.7.0
  build: ^1.3.0
  source_gen: ^0.9.7+1
  analyzer: ^0.39.14

dev_dependencies:
  pedantic:
  test:
  build_config:
  build_runner:
